### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by stomioka** [sassoftware/loguccino#1]
The SAS documentation* refers to this repo, but the repo is empty.
*https://go.documentation.sas.com/doc/en/log4j/1.0/n0emauiusfguyrn1wt2djefsqgtu.htm

**Comment by boemska-nik** [comment]
Hi @stomioka - the repo was indeed empty when the documentation from SAS went out. Looks like it was a race condition.

It's no longer empty so I'm closing this. Thanks for raising it.
