### ISSUE TITLE
Scan doesn't follow symlinks

### ISSUE THREAD

**Issue by damcwa** [sassoftware/loguccino#10]
It seems like the scan option doesn't work if you specify a symlink. For example if I have the home path specified as /sso/sfw/sas/940M6 where 940M6 is a symlink to 940A, it appears to run but doesn't actually scan anything. If I run it directly on 940A it works as expected.

**Comment by boemska-nik** [comment]
This is intentional, as following symlinks could cause undesired behaviour (altering other filesystems, etc). Do you need an option implemented to follow symlinks?

**Comment by damcwa** [comment]
Well, at least in the remote managed environments I currently service it would be helpful to have an option. We do use them quite frequently.

**Comment by boemska-nik** [comment]
@damcwa I'm gonna close this one as a wontfix. If you feel it's still something worth working on let us know and we can reopen.
