### ISSUE TITLE
Incorrect command for Viya 3.x

### ISSUE THREAD

**Issue by JMPoilane** [sassoftware/loguccino#12]
You need to use --no-compress option in command line for Viya 3.x as documented in SAS documentation, so please can you align GitHub documentation 
path-to-bin-java -jar loguccino-version.jar patch --no-compress  path-to-myOutput.csv

**Comment by boemska-nik** [comment]
Thanks for the suggestion @JMPoilane. I've added a note at the beginning of the readme.
