### ISSUE TITLE
Patching fails to preserve original owner, group, permissions.

### ISSUE THREAD

**Issue by utoddl** [sassoftware/loguccino#17]
Patching fails to preserve original owner, group, permissions.

**Comment by boemska-nik** [comment]
This is how the current version works. The release we're testing at the moment (3.2.0) will preserve POSIX permissions for patched files.

Will leave this open until the 3.2.0 release.

**Comment by boemska-nik** [comment]
@utoddl This should be resolved now. Have a play and let us know. If it doesn't do what you need feel free to reopen the issue.
